source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

target 'FFToolsKit_Example' do
  pod 'FFToolsKit', :path => '../'
  pod 'MBProgressHUD'
  pod 'FMDB'
  
  
  target 'FFToolsKit_Tests' do
    inherit! :search_paths

    
  end
end
